declare module '*.css';
declare module '*.less';
declare module 'html-webpack-plugin';
declare module 'mini-css-extract-plugin';
declare module 'webpack-dev-middleware';
declare module 'express';
declare module 'webpack-hot-middleware';
declare module 'copy-webpack-plugin';
declare module 'clean-webpack-plugin';
